"""Add company table and linked with User, Chatbots and Dataset

Revision ID: 35fdf805b772
Revises: ebdaeba615fc
Create Date: 2019-10-17 00:53:49.807395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35fdf805b772'
down_revision = 'ebdaeba615fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('chatbots', sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_chatbots_company_id'), 'chatbots', ['company_id'], unique=False)
    op.create_foreign_key(None, 'chatbots', 'company', ['company_id'], ['company_id'])
    op.add_column('datasets', sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_datasets_company_id'), 'datasets', ['company_id'], unique=False)
    op.create_foreign_key(None, 'datasets', 'company', ['company_id'], ['company_id'])
    op.add_column('users', sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_foreign_key(None, 'users', 'company', ['company_id'], ['company_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_column('users', 'company_id')
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.drop_index(op.f('ix_datasets_company_id'), table_name='datasets')
    op.drop_column('datasets', 'company_id')
    op.drop_constraint(None, 'chatbots', type_='foreignkey')
    op.drop_index(op.f('ix_chatbots_company_id'), table_name='chatbots')
    op.drop_column('chatbots', 'company_id')
    op.drop_table('company')
    # ### end Alembic commands ###
