"""Set company nullable false

Revision ID: cd31b15ae668
Revises: 35fdf805b772
Create Date: 2019-10-17 02:26:57.218126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd31b15ae668'
down_revision = '35fdf805b772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatbots', 'company_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('datasets', 'company_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('users', 'company_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'company_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('datasets', 'company_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('chatbots', 'company_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
